[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
