"""
Market Pulse Data Models
"""
from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class PulseEvent(BaseModel):
    """Single pulse event"""
    timestamp: str
    ticker: str = "MARKET"
    price: float
    volume: float
    velocity: float
    volume_surge: Dict[str, Any]
    volatility_burst: Dict[str, Any]
    breadth: Dict[str, Any]
    stress: float = Field(ge=0.0, le=1.0)
    regime: str


class PulseIndicator(BaseModel):
    """Individual pulse indicator"""
    name: str
    value: float
    magnitude: str
    description: str


class MarketPulseResponse(BaseModel):
    """Current market pulse state"""
    timestamp: str
    stress_score: float = Field(ge=0.0, le=1.0)
    regime: str
    indicators: List[PulseIndicator]
    velocity: float
    volume_surge: Dict[str, Any]
    volatility_burst: Dict[str, Any]
    breadth: Dict[str, Any]


class PulseHistoryResponse(BaseModel):
    """Historical pulse data"""
    events: List[PulseEvent]
    start_date: str
    end_date: str
    count: int


class DailySummary(BaseModel):
    """Daily summary generated by agent"""
    date: str
    summary: str
    key_events: List[str]
    learnings: List[str]
    regime: str
    stress_avg: float
    recommendations: Optional[List[str]] = None


class DailySummaryResponse(BaseModel):
    """Daily summary response"""
    summaries: List[DailySummary]
    count: int

