"""
SQLAlchemy models for Tokimeki Trading Simulation System
Backward compatible - additive only
"""
from datetime import datetime, date
from typing import Optional, Dict, Any
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, JSON, ForeignKey, Index, Date, UniqueConstraint
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from .database import Base


class PricesDaily(Base):
    """Daily OHLCV price data for stocks"""
    __tablename__ = "prices_daily"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer, default=0)
    adjusted_close = Column(Float, nullable=True)  # Adjusted for splits/dividends
    split_factor = Column(Float, default=1.0)  # Split adjustment factor
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    __table_args__ = (
        UniqueConstraint('symbol', 'date', name='uq_prices_daily_symbol_date'),
        Index('idx_prices_daily_symbol_date', 'symbol', 'date'),
    )


class OptionsSnapshotDaily(Base):
    """Daily options chain snapshot"""
    __tablename__ = "options_snapshot_daily"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    snapshot_json = Column(JSON, nullable=False)  # Full chain snapshot
    iv_median = Column(Float, nullable=True)  # Median IV across chain
    iv_near = Column(Float, nullable=True)  # Near-term IV (7-21 days)
    iv_far = Column(Float, nullable=True)  # Far-term IV (60-120 days)
    iv_slope = Column(Float, nullable=True)  # iv_near - iv_far
    iv_bucket_quality = Column(String(20), nullable=True)  # Quality flag for IV buckets
    total_call_volume = Column(Integer, default=0)
    total_put_volume = Column(Integer, default=0)
    total_call_oi = Column(Integer, default=0)
    total_put_oi = Column(Integer, default=0)
    unusual_count = Column(Integer, default=0)  # Count of unusual flags
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    __table_args__ = (
        UniqueConstraint('symbol', 'date', name='uq_options_snapshot_daily_symbol_date'),
        Index('idx_options_snapshot_daily_symbol_date', 'symbol', 'date'),
    )


class FeaturesDaily(Base):
    """Daily engineered features for strategies"""
    __tablename__ = "features_daily"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    
    # Realized volatility
    rv20 = Column(Float, nullable=True)  # 20-day annualized realized vol
    rv60 = Column(Float, nullable=True)  # 60-day annualized realized vol
    
    # Range/movement
    atr14 = Column(Float, nullable=True)  # 14-day ATR
    
    # Options-derived
    iv_median = Column(Float, nullable=True)  # Median IV
    iv_slope = Column(Float, nullable=True)  # Term structure slope
    cp_vol_ratio = Column(Float, nullable=True)  # Call/put volume ratio
    cp_oi_ratio = Column(Float, nullable=True)  # Call/put OI ratio
    unusual_count = Column(Integer, default=0)
    
    # Percentiles (rolling 504 trading days)
    rv20_pct = Column(Float, nullable=True)  # Percentile rank of rv20
    atr14_pct = Column(Float, nullable=True)  # Percentile rank of atr14
    iv_median_pct = Column(Float, nullable=True)  # Percentile rank of iv_median
    
    # Quality flags
    percentile_quality = Column(String(20), nullable=True)  # e.g., "sufficient", "insufficient"
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    __table_args__ = (
        UniqueConstraint('symbol', 'date', name='uq_features_daily_symbol_date'),
        Index('idx_features_daily_symbol_date', 'symbol', 'date'),
    )


class SignalsDaily(Base):
    """Daily trading signals generated by strategies"""
    __tablename__ = "signals_daily"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(String(100), nullable=False, index=True)  # e.g., "vol_regime_v1"
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    signal = Column(String(10), nullable=False)  # LONG, SHORT, FLAT
    target_position = Column(Float, nullable=False)  # Target position size (fraction of NAV)
    reason_json = Column(JSON, nullable=True)  # Explainability JSON
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        UniqueConstraint('strategy_id', 'symbol', 'date', name='uq_signals_daily_strategy_symbol_date'),
        Index('idx_signals_daily_strategy_symbol_date', 'strategy_id', 'symbol', 'date'),
    )


class Trades(Base):
    """Individual trades executed in simulation"""
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(String(100), nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    side = Column(String(10), nullable=False)  # LONG, SHORT
    quantity = Column(Float, nullable=False)  # Number of shares
    price = Column(Float, nullable=False)  # Execution price
    timing = Column(String(20), default="MOC")  # MOC, NEXT_OPEN
    signal_id = Column(Integer, ForeignKey("signals_daily.id"), nullable=True)  # Link to signal
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_trades_strategy_symbol_date', 'strategy_id', 'symbol', 'date'),
    )


class PortfolioDaily(Base):
    """Daily portfolio state and performance"""
    __tablename__ = "portfolio_daily"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(String(100), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    nav = Column(Float, nullable=False)  # Net Asset Value
    cash = Column(Float, nullable=False)  # Cash balance
    positions_json = Column(JSON, nullable=False)  # {symbol: quantity} dict
    daily_pnl = Column(Float, nullable=True)  # Daily P&L
    cumulative_pnl = Column(Float, nullable=True)  # Cumulative P&L
    drawdown = Column(Float, nullable=True)  # Current drawdown %
    max_drawdown = Column(Float, nullable=True)  # Maximum drawdown %
    risk_state_json = Column(JSON, nullable=True)  # Risk control state
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    __table_args__ = (
        UniqueConstraint('strategy_id', 'date', name='uq_portfolio_daily_strategy_date'),
        Index('idx_portfolio_daily_strategy_date', 'strategy_id', 'date'),
    )


class StrategyMetadata(Base):
    """Strategy metadata and configurations"""
    __tablename__ = "strategy_metadata"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(String(100), unique=True, nullable=False, index=True)
    name = Column(String(200), nullable=False)
    version = Column(String(50), nullable=False)
    params_json = Column(JSON, nullable=False)  # Strategy parameters
    description = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())


class RegimeStates(Base):
    """Regime ON/OFF states per day for explainability"""
    __tablename__ = "regime_states"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(String(100), nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    regime_on = Column(Boolean, nullable=False)  # True if regime is active
    reasons_json = Column(JSON, nullable=True)  # Detailed regime reasons
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        UniqueConstraint('strategy_id', 'symbol', 'date', name='uq_regime_states_strategy_symbol_date'),
        Index('idx_regime_states_strategy_symbol_date', 'strategy_id', 'symbol', 'date'),
    )

